language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
# branches:
#   only:
#   - master
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu # --remote-debugging-port=9222 http://localhost &
script:
 - ng e2e